import Head from "next/head";
// eslint-disable-next-line import/no-extraneous-dependencies
import { light } from "@acerohernan/pancakeui";
// import { light } from "@pancakeswap/uikit";
// import { light as aceroLight } from "@acerohernan/ui-kit";

export default function Home() {
  return (
    <>
      <Head>
        <title>Acero&apos;s Pancake</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Web</h1>

        <pre>{JSON.stringify(light, null, 2)}</pre>
      </main>
    </>
  );
}
