import Head from "next/head";
import { Button, Flex, IconButton, LogoIcon, Modal, useModal } from "@acerohernan/pancakeui";
import { ModalProps } from "@pancakeswap/uikit";

const ModalExample: React.FC<ModalProps> = ({ title, onDismiss }) => (
  <Modal onDismiss={onDismiss} title={title}>
    <h1>Hi everyone!</h1>
    <Button>I do nothing</Button>
  </Modal>
);

export default function Home() {
  const [onPresent] = useModal(<ModalExample title="Title example" />);

  return (
    <>
      <Head>
        <title>Acero&apos;s Pancake</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Web</h1>
        <Flex alignItems="center" style={{ gap: "10px" }}>
          <Button label="Button" onClick={onPresent}>
            Click here
          </Button>
          <IconButton>
            <LogoIcon spin />
          </IconButton>
        </Flex>
      </main>
    </>
  );
}
