import Head from "next/head";
import { light, Button } from "@acerohernan/pancakeui";
import { light as pancakeLight } from "@pancakeswap/uikit";

export default function Home() {
  return (
    <>
      <Head>
        <title>Acero&apos;s Pancake</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Web</h1>

        <pre>{JSON.stringify(light, null, 2)}</pre>
        <Button label="Button" />
        <pre>{JSON.stringify(pancakeLight, null, 2)}</pre>
      </main>
    </>
  );
}
